# Add Source-Level Retrieval Metrics

This notebook does **not** query Qdrant again. It reads existing evaluation outputs and adds source-level metrics:

- `source_recall_at_3/10/20`: any retrieved item has the gold evidence URL.
- `image_source_recall_at_3/10/20`: any retrieved **image** item has the gold evidence URL.

The goal is to check whether image retrieval finds the correct article/source even when it does not match the exact gold image path.

In [1]:
from __future__ import annotations

from pathlib import Path
import pandas as pd
from tqdm.auto import tqdm

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name in {"database", "refined"}:
    PROJECT_ROOT = PROJECT_ROOT.parent

OUTPUT_DIR = PROJECT_ROOT / "database" / "retrieval_eval_outputs"
DETAILS_CSV = OUTPUT_DIR / "retrieval_results_long.csv"
CLAIM_METRICS_CSV = OUTPUT_DIR / "claim_metrics_long.csv"
SUMMARY_CSV = OUTPUT_DIR / "metrics_summary.csv"

UPDATED_DETAILS_CSV = OUTPUT_DIR / "retrieval_results_long_with_source_metrics.csv"
UPDATED_CLAIM_METRICS_CSV = OUTPUT_DIR / "claim_metrics_long_with_source_metrics.csv"
UPDATED_SUMMARY_CSV = OUTPUT_DIR / "metrics_summary_with_source_metrics.csv"

TOP_K_VALUES = [3, 10, 20]
CHUNKSIZE = 200_000

print("Output dir:", OUTPUT_DIR)
print("Details exists:", DETAILS_CSV.exists(), DETAILS_CSV)
print("Claim metrics exists:", CLAIM_METRICS_CSV.exists(), CLAIM_METRICS_CSV)
print("Summary exists:", SUMMARY_CSV.exists(), SUMMARY_CSV)

Output dir: D:\FactCheckPipeline\database\retrieval_eval_outputs
Details exists: True D:\FactCheckPipeline\database\retrieval_eval_outputs\retrieval_results_long.csv
Claim metrics exists: True D:\FactCheckPipeline\database\retrieval_eval_outputs\claim_metrics_long.csv
Summary exists: True D:\FactCheckPipeline\database\retrieval_eval_outputs\metrics_summary.csv

C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Helpers

In [2]:
def normalize_url(value) -> str:
    text = str(value or "").strip().lower()
    return text.rstrip("/")

def add_source_flags(chunk: pd.DataFrame) -> pd.DataFrame:
    chunk = chunk.copy()
    retrieved_url = chunk["url"].fillna("").map(normalize_url)
    gold_url = chunk["gold_text_url"].fillna("").map(normalize_url)
    chunk["source_hit"] = (retrieved_url != "") & (gold_url != "") & (retrieved_url == gold_url)
    chunk["image_source_hit"] = chunk["source_hit"] & chunk["modality"].fillna("").eq("image")
    return chunk

def summarize_claim_group(group: pd.DataFrame) -> dict:
    out = {}
    group = group.sort_values("rank")
    for k in TOP_K_VALUES:
        top = group[group["rank"] <= k]
        out[f"source_recall_at_{k}"] = int(top["source_hit"].any())
        out[f"image_source_recall_at_{k}"] = int(top["image_source_hit"].any())
    first_source_rank = group.loc[group["source_hit"], "rank"].min() if group["source_hit"].any() else 0
    first_image_source_rank = group.loc[group["image_source_hit"], "rank"].min() if group["image_source_hit"].any() else 0
    out["first_source_hit_rank"] = int(first_source_rank or 0)
    out["first_image_source_hit_rank"] = int(first_image_source_rank or 0)
    out["source_mrr_at_3"] = (1 / first_source_rank) if first_source_rank and first_source_rank <= 3 else 0.0
    out["image_source_mrr_at_3"] = (1 / first_image_source_rank) if first_image_source_rank and first_image_source_rank <= 3 else 0.0
    return out

## Add Row-Level Source Flags

`retrieval_results_long.csv` can be large, so this cell streams it by chunks and writes a new file.

In [3]:
if UPDATED_DETAILS_CSV.exists():
    UPDATED_DETAILS_CSV.unlink()

first = True
usecols = None
reader = pd.read_csv(DETAILS_CSV, chunksize=CHUNKSIZE)
for chunk in tqdm(reader, desc="Adding source flags"):
    chunk = add_source_flags(chunk)
    chunk.to_csv(UPDATED_DETAILS_CSV, mode="w" if first else "a", header=first, index=False, encoding="utf-8-sig")
    first = False

print("Wrote", UPDATED_DETAILS_CSV)

Adding source flags: 0it [00:00, ?it/s]

C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\std.py:1181: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  for obj in iterable:

Adding source flags: 1it [00:16, 16.53s/it]

C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\std.py:1181: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  for obj in iterable:

Adding source flags: 2it [00:32, 16.27s/it]

Adding source flags: 3it [00:33,  9.42s/it]

Adding source flags: 3it [00:33, 11.30s/it]

Wrote D:\FactCheckPipeline\database\retrieval_eval_outputs\retrieval_results_long_with_source_metrics.csv

## Compute Per-Claim Source Metrics

In [4]:
key_cols = [
    "experiment_id", "refiner", "collection", "image_variant", "use_reranker",
    "id", "claim", "label", "gold_text_url", "gold_image_path",
]
source_cols = [*key_cols, "rank", "source_hit", "image_source_hit"]

parts = []
for chunk in tqdm(pd.read_csv(UPDATED_DETAILS_CSV, usecols=source_cols, chunksize=CHUNKSIZE), desc="Loading flagged rows"):
    parts.append(chunk)
details = pd.concat(parts, ignore_index=True)
print(details.shape)

claim_source_metrics = []
for keys, group in tqdm(details.groupby(key_cols, dropna=False), desc="Per-claim metrics"):
    row = dict(zip(key_cols, keys))
    row.update(summarize_claim_group(group))
    claim_source_metrics.append(row)

claim_source_metrics = pd.DataFrame(claim_source_metrics)
claim_source_metrics.head()

Loading flagged rows: 0it [00:00, ?it/s]

Loading flagged rows: 1it [00:04,  4.06s/it]

Loading flagged rows: 2it [00:08,  4.03s/it]

Loading flagged rows: 3it [00:08,  2.33s/it]

Loading flagged rows: 3it [00:08,  2.79s/it]

(413760, 13)

Per-claim metrics:   0%|          | 0/20688 [00:00<?, ?it/s]

Per-claim metrics:   0%|          | 1/20688 [00:00<4:19:36,  1.33it/s]

Per-claim metrics:   0%|          | 68/20688 [00:00<03:11, 107.95it/s]

Per-claim metrics:   1%|          | 136/20688 [00:00<01:36, 213.61it/s]

Per-claim metrics:   1%|          | 206/20688 [00:01<01:04, 315.23it/s]

Per-claim metrics:   1%|▏         | 275/20688 [00:01<00:50, 400.31it/s]

Per-claim metrics:   2%|▏         | 338/20688 [00:01<00:45, 449.75it/s]

Per-claim metrics:   2%|▏         | 408/20688 [00:01<00:39, 514.21it/s]

Per-claim metrics:   2%|▏         | 479/20688 [00:01<00:35, 565.38it/s]

Per-claim metrics:   3%|▎         | 549/20688 [00:01<00:33, 601.43it/s]

Per-claim metrics:   3%|▎         | 617/20688 [00:01<00:32, 613.32it/s]

Per-claim metrics:   3%|▎         | 684/20688 [00:01<00:32, 616.98it/s]

Per-claim metrics:   4%|▎         | 750/20688 [00:01<00:33, 595.26it/s]

Per-claim metrics:   4%|▍         | 821/20688 [00:01<00:31, 625.25it/s]

Per-claim metrics:   4%|▍         | 887/20688 [00:02<00:31, 632.35it/s]

Per-claim metrics:   5%|▍         | 957/20688 [00:02<00:30, 648.98it/s]

Per-claim metrics:   5%|▍         | 1028/20688 [00:02<00:29, 664.53it/s]

Per-claim metrics:   5%|▌         | 1097/20688 [00:02<00:29, 671.90it/s]

Per-claim metrics:   6%|▌         | 1165/20688 [00:02<00:29, 657.78it/s]

Per-claim metrics:   6%|▌         | 1232/20688 [00:02<00:29, 656.51it/s]

Per-claim metrics:   6%|▋         | 1298/20688 [00:02<00:29, 650.11it/s]

Per-claim metrics:   7%|▋         | 1364/20688 [00:02<00:29, 648.01it/s]

Per-claim metrics:   7%|▋         | 1429/20688 [00:02<00:30, 641.35it/s]

Per-claim metrics:   7%|▋         | 1497/20688 [00:03<00:29, 651.24it/s]

Per-claim metrics:   8%|▊         | 1563/20688 [00:03<00:30, 627.07it/s]

Per-claim metrics:   8%|▊         | 1628/20688 [00:03<00:30, 632.48it/s]

Per-claim metrics:   8%|▊         | 1695/20688 [00:03<00:29, 640.50it/s]

Per-claim metrics:   9%|▊         | 1761/20688 [00:03<00:29, 645.70it/s]

Per-claim metrics:   9%|▉         | 1829/20688 [00:03<00:28, 654.00it/s]

Per-claim metrics:   9%|▉         | 1900/20688 [00:03<00:28, 668.90it/s]

Per-claim metrics:  10%|▉         | 1970/20688 [00:03<00:27, 676.64it/s]

Per-claim metrics:  10%|▉         | 2041/20688 [00:03<00:27, 684.01it/s]

Per-claim metrics:  10%|█         | 2110/20688 [00:03<00:27, 670.46it/s]

Per-claim metrics:  11%|█         | 2181/20688 [00:04<00:27, 681.32it/s]

Per-claim metrics:  11%|█         | 2250/20688 [00:04<00:27, 677.40it/s]

Per-claim metrics:  11%|█         | 2318/20688 [00:04<00:27, 670.54it/s]

Per-claim metrics:  12%|█▏        | 2389/20688 [00:04<00:26, 680.15it/s]

Per-claim metrics:  12%|█▏        | 2458/20688 [00:04<00:27, 670.39it/s]

Per-claim metrics:  12%|█▏        | 2530/20688 [00:04<00:26, 683.52it/s]

Per-claim metrics:  13%|█▎        | 2599/20688 [00:04<00:26, 680.63it/s]

Per-claim metrics:  13%|█▎        | 2668/20688 [00:04<00:26, 682.86it/s]

Per-claim metrics:  13%|█▎        | 2737/20688 [00:04<00:26, 684.31it/s]

Per-claim metrics:  14%|█▎        | 2806/20688 [00:04<00:26, 680.42it/s]

Per-claim metrics:  14%|█▍        | 2875/20688 [00:05<00:26, 673.30it/s]

Per-claim metrics:  14%|█▍        | 2943/20688 [00:05<00:26, 663.51it/s]

Per-claim metrics:  15%|█▍        | 3011/20688 [00:05<00:26, 666.65it/s]

Per-claim metrics:  15%|█▍        | 3079/20688 [00:05<00:26, 669.89it/s]

Per-claim metrics:  15%|█▌        | 3147/20688 [00:05<00:26, 662.50it/s]

Per-claim metrics:  16%|█▌        | 3218/20688 [00:05<00:25, 675.53it/s]

Per-claim metrics:  16%|█▌        | 3287/20688 [00:05<00:25, 679.38it/s]

Per-claim metrics:  16%|█▌        | 3355/20688 [00:05<00:25, 679.52it/s]

Per-claim metrics:  17%|█▋        | 3428/20688 [00:05<00:24, 691.66it/s]

Per-claim metrics:  17%|█▋        | 3498/20688 [00:06<00:25, 674.55it/s]

Per-claim metrics:  17%|█▋        | 3566/20688 [00:06<00:26, 648.33it/s]

Per-claim metrics:  18%|█▊        | 3637/20688 [00:06<00:25, 663.66it/s]

Per-claim metrics:  18%|█▊        | 3705/20688 [00:06<00:25, 667.03it/s]

Per-claim metrics:  18%|█▊        | 3772/20688 [00:06<00:25, 655.90it/s]

Per-claim metrics:  19%|█▊        | 3840/20688 [00:06<00:25, 660.70it/s]

Per-claim metrics:  19%|█▉        | 3909/20688 [00:06<00:25, 667.04it/s]

Per-claim metrics:  19%|█▉        | 3979/20688 [00:06<00:24, 675.34it/s]

Per-claim metrics:  20%|█▉        | 4048/20688 [00:06<00:24, 675.74it/s]

Per-claim metrics:  20%|█▉        | 4118/20688 [00:06<00:24, 680.86it/s]

Per-claim metrics:  20%|██        | 4187/20688 [00:07<00:24, 670.53it/s]

Per-claim metrics:  21%|██        | 4256/20688 [00:07<00:24, 674.05it/s]

Per-claim metrics:  21%|██        | 4324/20688 [00:07<00:24, 658.49it/s]

Per-claim metrics:  21%|██        | 4392/20688 [00:07<00:24, 664.15it/s]

Per-claim metrics:  22%|██▏       | 4462/20688 [00:07<00:24, 672.48it/s]

Per-claim metrics:  22%|██▏       | 4530/20688 [00:07<00:24, 666.16it/s]

Per-claim metrics:  22%|██▏       | 4598/20688 [00:07<00:24, 667.55it/s]

Per-claim metrics:  23%|██▎       | 4665/20688 [00:07<00:24, 657.88it/s]

Per-claim metrics:  23%|██▎       | 4731/20688 [00:07<00:24, 652.72it/s]

Per-claim metrics:  23%|██▎       | 4798/20688 [00:07<00:24, 656.05it/s]

Per-claim metrics:  24%|██▎       | 4867/20688 [00:08<00:23, 663.42it/s]

Per-claim metrics:  24%|██▍       | 4938/20688 [00:08<00:23, 676.78it/s]

Per-claim metrics:  24%|██▍       | 5006/20688 [00:08<00:23, 664.96it/s]

Per-claim metrics:  25%|██▍       | 5073/20688 [00:08<00:23, 666.17it/s]

Per-claim metrics:  25%|██▍       | 5140/20688 [00:08<00:23, 659.49it/s]

Per-claim metrics:  25%|██▌       | 5206/20688 [00:08<00:23, 659.28it/s]

Per-claim metrics:  26%|██▌       | 5278/20688 [00:08<00:22, 676.58it/s]

Per-claim metrics:  26%|██▌       | 5346/20688 [00:08<00:23, 661.96it/s]

Per-claim metrics:  26%|██▌       | 5413/20688 [00:08<00:23, 656.82it/s]

Per-claim metrics:  26%|██▋       | 5479/20688 [00:08<00:23, 654.67it/s]

Per-claim metrics:  27%|██▋       | 5545/20688 [00:09<00:23, 648.38it/s]

Per-claim metrics:  27%|██▋       | 5631/20688 [00:09<00:21, 708.60it/s]

Per-claim metrics:  28%|██▊       | 5736/20688 [00:09<00:18, 808.04it/s]

Per-claim metrics:  28%|██▊       | 5843/20688 [00:09<00:16, 884.90it/s]

Per-claim metrics:  29%|██▉       | 5950/20688 [00:09<00:15, 937.45it/s]

Per-claim metrics:  29%|██▉       | 6044/20688 [00:09<00:15, 928.73it/s]

Per-claim metrics:  30%|██▉       | 6151/20688 [00:09<00:15, 969.03it/s]

Per-claim metrics:  30%|███       | 6264/20688 [00:09<00:14, 1014.21it/s]

Per-claim metrics:  31%|███       | 6377/20688 [00:09<00:13, 1046.21it/s]

Per-claim metrics:  31%|███▏      | 6485/20688 [00:10<00:13, 1054.06it/s]

Per-claim metrics:  32%|███▏      | 6594/20688 [00:10<00:13, 1062.82it/s]

Per-claim metrics:  32%|███▏      | 6701/20688 [00:10<00:13, 1062.55it/s]

Per-claim metrics:  33%|███▎      | 6808/20688 [00:10<00:13, 1056.49it/s]

Per-claim metrics:  33%|███▎      | 6917/20688 [00:10<00:12, 1063.68it/s]

Per-claim metrics:  34%|███▍      | 7025/20688 [00:10<00:12, 1065.86it/s]

Per-claim metrics:  34%|███▍      | 7133/20688 [00:10<00:12, 1066.64it/s]

Per-claim metrics:  35%|███▍      | 7240/20688 [00:10<00:13, 1012.22it/s]

Per-claim metrics:  35%|███▌      | 7343/20688 [00:10<00:13, 1016.33it/s]

Per-claim metrics:  36%|███▌      | 7446/20688 [00:10<00:12, 1019.07it/s]

Per-claim metrics:  36%|███▋      | 7550/20688 [00:11<00:12, 1025.02it/s]

Per-claim metrics:  37%|███▋      | 7657/20688 [00:11<00:12, 1037.50it/s]

Per-claim metrics:  38%|███▊      | 7766/20688 [00:11<00:12, 1050.42it/s]

Per-claim metrics:  38%|███▊      | 7875/20688 [00:11<00:12, 1059.62it/s]

Per-claim metrics:  39%|███▊      | 7986/20688 [00:11<00:11, 1072.29it/s]

Per-claim metrics:  39%|███▉      | 8096/20688 [00:11<00:11, 1079.41it/s]

Per-claim metrics:  40%|███▉      | 8204/20688 [00:11<00:11, 1073.65it/s]

Per-claim metrics:  40%|████      | 8313/20688 [00:11<00:11, 1076.35it/s]

Per-claim metrics:  41%|████      | 8424/20688 [00:11<00:11, 1085.67it/s]

Per-claim metrics:  41%|████      | 8533/20688 [00:11<00:11, 1079.49it/s]

Per-claim metrics:  42%|████▏     | 8643/20688 [00:12<00:11, 1083.85it/s]

Per-claim metrics:  42%|████▏     | 8752/20688 [00:12<00:11, 1074.10it/s]

Per-claim metrics:  43%|████▎     | 8862/20688 [00:12<00:10, 1080.15it/s]

Per-claim metrics:  43%|████▎     | 8971/20688 [00:12<00:10, 1081.38it/s]

Per-claim metrics:  44%|████▍     | 9081/20688 [00:12<00:10, 1086.39it/s]

Per-claim metrics:  44%|████▍     | 9190/20688 [00:12<00:10, 1075.78it/s]

Per-claim metrics:  45%|████▍     | 9298/20688 [00:12<00:10, 1069.24it/s]

Per-claim metrics:  45%|████▌     | 9408/20688 [00:12<00:10, 1077.11it/s]

Per-claim metrics:  46%|████▌     | 9518/20688 [00:12<00:10, 1080.85it/s]

Per-claim metrics:  47%|████▋     | 9629/20688 [00:12<00:10, 1086.73it/s]

Per-claim metrics:  47%|████▋     | 9740/20688 [00:13<00:10, 1093.42it/s]

Per-claim metrics:  48%|████▊     | 9850/20688 [00:13<00:10, 1029.07it/s]

Per-claim metrics:  48%|████▊     | 9954/20688 [00:13<00:11, 934.75it/s]

Per-claim metrics:  49%|████▊     | 10060/20688 [00:13<00:10, 967.39it/s]

Per-claim metrics:  49%|████▉     | 10159/20688 [00:13<00:10, 971.19it/s]

Per-claim metrics:  50%|████▉     | 10266/20688 [00:13<00:10, 998.13it/s]

Per-claim metrics:  50%|█████     | 10367/20688 [00:13<00:10, 976.37it/s]

Per-claim metrics:  51%|█████     | 10466/20688 [00:13<00:10, 969.96it/s]

Per-claim metrics:  51%|█████     | 10564/20688 [00:13<00:10, 956.04it/s]

Per-claim metrics:  52%|█████▏    | 10660/20688 [00:14<00:10, 953.84it/s]

Per-claim metrics:  52%|█████▏    | 10756/20688 [00:14<00:10, 943.28it/s]

Per-claim metrics:  52%|█████▏    | 10854/20688 [00:14<00:10, 953.45it/s]

Per-claim metrics:  53%|█████▎    | 10954/20688 [00:14<00:10, 965.24it/s]

Per-claim metrics:  53%|█████▎    | 11051/20688 [00:14<00:10, 929.74it/s]

Per-claim metrics:  54%|█████▍    | 11147/20688 [00:14<00:10, 936.40it/s]

Per-claim metrics:  54%|█████▍    | 11251/20688 [00:14<00:09, 966.14it/s]

Per-claim metrics:  55%|█████▍    | 11354/20688 [00:14<00:09, 983.15it/s]

Per-claim metrics:  55%|█████▌    | 11459/20688 [00:14<00:09, 1001.35it/s]

Per-claim metrics:  56%|█████▌    | 11571/20688 [00:14<00:08, 1035.27it/s]

Per-claim metrics:  56%|█████▋    | 11679/20688 [00:15<00:08, 1048.22it/s]

Per-claim metrics:  57%|█████▋    | 11787/20688 [00:15<00:08, 1057.68it/s]

Per-claim metrics:  58%|█████▊    | 11898/20688 [00:15<00:08, 1071.60it/s]

Per-claim metrics:  58%|█████▊    | 12007/20688 [00:15<00:08, 1075.54it/s]

Per-claim metrics:  59%|█████▊    | 12118/20688 [00:15<00:07, 1084.22it/s]

Per-claim metrics:  59%|█████▉    | 12227/20688 [00:15<00:08, 1050.61it/s]

Per-claim metrics:  60%|█████▉    | 12337/20688 [00:15<00:07, 1062.62it/s]

Per-claim metrics:  60%|██████    | 12444/20688 [00:15<00:07, 1050.83it/s]

Per-claim metrics:  61%|██████    | 12550/20688 [00:15<00:07, 1033.19it/s]

Per-claim metrics:  61%|██████    | 12658/20688 [00:15<00:07, 1044.93it/s]

Per-claim metrics:  62%|██████▏   | 12770/20688 [00:16<00:07, 1064.96it/s]

Per-claim metrics:  62%|██████▏   | 12881/20688 [00:16<00:07, 1076.79it/s]

Per-claim metrics:  63%|██████▎   | 12992/20688 [00:16<00:07, 1084.05it/s]

Per-claim metrics:  63%|██████▎   | 13101/20688 [00:16<00:06, 1085.14it/s]

Per-claim metrics:  64%|██████▍   | 13213/20688 [00:16<00:06, 1092.86it/s]

Per-claim metrics:  64%|██████▍   | 13326/20688 [00:16<00:06, 1103.86it/s]

Per-claim metrics:  65%|██████▍   | 13437/20688 [00:16<00:06, 1105.33it/s]

Per-claim metrics:  65%|██████▌   | 13548/20688 [00:16<00:06, 1097.53it/s]

Per-claim metrics:  66%|██████▌   | 13658/20688 [00:16<00:06, 1077.39it/s]

Per-claim metrics:  67%|██████▋   | 13766/20688 [00:16<00:06, 1073.67it/s]

Per-claim metrics:  67%|██████▋   | 13875/20688 [00:17<00:06, 1078.14it/s]

Per-claim metrics:  68%|██████▊   | 13987/20688 [00:17<00:06, 1090.34it/s]

Per-claim metrics:  68%|██████▊   | 14098/20688 [00:17<00:06, 1094.96it/s]

Per-claim metrics:  69%|██████▊   | 14208/20688 [00:17<00:05, 1095.20it/s]

Per-claim metrics:  69%|██████▉   | 14318/20688 [00:17<00:05, 1088.99it/s]

Per-claim metrics:  70%|██████▉   | 14428/20688 [00:17<00:05, 1090.45it/s]

Per-claim metrics:  70%|███████   | 14538/20688 [00:17<00:05, 1089.96it/s]

Per-claim metrics:  71%|███████   | 14648/20688 [00:17<00:05, 1089.42it/s]

Per-claim metrics:  71%|███████▏  | 14757/20688 [00:17<00:05, 1074.84it/s]

Per-claim metrics:  72%|███████▏  | 14868/20688 [00:18<00:05, 1083.11it/s]

Per-claim metrics:  72%|███████▏  | 14977/20688 [00:18<00:05, 1084.83it/s]

Per-claim metrics:  73%|███████▎  | 15087/20688 [00:18<00:05, 1088.27it/s]

Per-claim metrics:  73%|███████▎  | 15199/20688 [00:18<00:05, 1095.73it/s]

Per-claim metrics:  74%|███████▍  | 15309/20688 [00:18<00:04, 1087.74it/s]

Per-claim metrics:  75%|███████▍  | 15421/20688 [00:18<00:04, 1097.17it/s]

Per-claim metrics:  75%|███████▌  | 15531/20688 [00:18<00:04, 1094.27it/s]

Per-claim metrics:  76%|███████▌  | 15641/20688 [00:18<00:04, 1070.46it/s]

Per-claim metrics:  76%|███████▌  | 15751/20688 [00:18<00:04, 1076.82it/s]

Per-claim metrics:  77%|███████▋  | 15859/20688 [00:18<00:04, 1061.41it/s]

Per-claim metrics:  77%|███████▋  | 15966/20688 [00:19<00:04, 1061.20it/s]

Per-claim metrics:  78%|███████▊  | 16073/20688 [00:19<00:04, 1063.61it/s]

Per-claim metrics:  78%|███████▊  | 16184/20688 [00:19<00:04, 1076.43it/s]

Per-claim metrics:  79%|███████▉  | 16292/20688 [00:19<00:04, 1076.88it/s]

Per-claim metrics:  79%|███████▉  | 16403/20688 [00:19<00:03, 1085.67it/s]

Per-claim metrics:  80%|███████▉  | 16513/20688 [00:19<00:03, 1086.25it/s]

Per-claim metrics:  80%|████████  | 16625/20688 [00:19<00:03, 1093.85it/s]

Per-claim metrics:  81%|████████  | 16736/20688 [00:19<00:03, 1097.15it/s]

Per-claim metrics:  81%|████████▏ | 16846/20688 [00:19<00:03, 1094.54it/s]

Per-claim metrics:  82%|████████▏ | 16956/20688 [00:19<00:03, 1084.04it/s]

Per-claim metrics:  82%|████████▏ | 17065/20688 [00:20<00:03, 1080.60it/s]

Per-claim metrics:  83%|████████▎ | 17175/20688 [00:20<00:03, 1083.81it/s]

Per-claim metrics:  84%|████████▎ | 17286/20688 [00:20<00:03, 1089.14it/s]

Per-claim metrics:  84%|████████▍ | 17396/20688 [00:20<00:03, 1091.25it/s]

Per-claim metrics:  85%|████████▍ | 17506/20688 [00:20<00:02, 1085.08it/s]

Per-claim metrics:  85%|████████▌ | 17615/20688 [00:20<00:02, 1077.90it/s]

Per-claim metrics:  86%|████████▌ | 17725/20688 [00:20<00:02, 1082.17it/s]

Per-claim metrics:  86%|████████▌ | 17837/20688 [00:20<00:02, 1090.90it/s]

Per-claim metrics:  87%|████████▋ | 17947/20688 [00:20<00:02, 1091.67it/s]

Per-claim metrics:  87%|████████▋ | 18059/20688 [00:20<00:02, 1098.84it/s]

Per-claim metrics:  88%|████████▊ | 18170/20688 [00:21<00:02, 1099.92it/s]

Per-claim metrics:  88%|████████▊ | 18282/20688 [00:21<00:02, 1105.31it/s]

Per-claim metrics:  89%|████████▉ | 18393/20688 [00:21<00:02, 1103.50it/s]

Per-claim metrics:  89%|████████▉ | 18505/20688 [00:21<00:01, 1107.95it/s]

Per-claim metrics:  90%|████████▉ | 18616/20688 [00:21<00:01, 1105.22it/s]

Per-claim metrics:  91%|█████████ | 18728/20688 [00:21<00:01, 1108.16it/s]

Per-claim metrics:  91%|█████████ | 18839/20688 [00:21<00:01, 1101.83it/s]

Per-claim metrics:  92%|█████████▏| 18950/20688 [00:21<00:01, 1096.09it/s]

Per-claim metrics:  92%|█████████▏| 19060/20688 [00:21<00:01, 1049.37it/s]

Per-claim metrics:  93%|█████████▎| 19166/20688 [00:21<00:01, 1032.43it/s]

Per-claim metrics:  93%|█████████▎| 19271/20688 [00:22<00:01, 1035.59it/s]

Per-claim metrics:  94%|█████████▎| 19380/20688 [00:22<00:01, 1050.64it/s]

Per-claim metrics:  94%|█████████▍| 19491/20688 [00:22<00:01, 1067.26it/s]

Per-claim metrics:  95%|█████████▍| 19598/20688 [00:22<00:01, 1060.77it/s]

Per-claim metrics:  95%|█████████▌| 19708/20688 [00:22<00:00, 1072.00it/s]

Per-claim metrics:  96%|█████████▌| 19816/20688 [00:22<00:00, 1009.99it/s]

Per-claim metrics:  96%|█████████▋| 19923/20688 [00:22<00:00, 1026.85it/s]

Per-claim metrics:  97%|█████████▋| 20031/20688 [00:22<00:00, 1041.40it/s]

Per-claim metrics:  97%|█████████▋| 20136/20688 [00:22<00:00, 908.07it/s]

Per-claim metrics:  98%|█████████▊| 20233/20688 [00:23<00:00, 923.29it/s]

Per-claim metrics:  98%|█████████▊| 20332/20688 [00:23<00:00, 941.54it/s]

Per-claim metrics:  99%|█████████▉| 20430/20688 [00:23<00:00, 949.42it/s]

Per-claim metrics:  99%|█████████▉| 20532/20688 [00:23<00:00, 967.44it/s]

Per-claim metrics: 100%|█████████▉| 20641/20688 [00:23<00:00, 1001.72it/s]

Per-claim metrics: 100%|██████████| 20688/20688 [00:23<00:00, 880.42it/s]

,experiment_id,refiner,collection,image_variant,use_reranker,id,claim,label,gold_text_url,gold_image_path,source_recall_at_3,image_source_recall_at_3,source_recall_at_10,image_source_recall_at_10,source_recall_at_20,image_source_recall_at_20,first_source_hit_rank,first_image_source_hit_rank,source_mrr_at_3,image_source_mrr_at_3
0,gemini-2.5-flash__fixed_size__clip__reranker_0,gemini-2.5-flash,fixed_size,clip,False,1,Công an tỉnh Thái Bình đã khởi tố 10 đối tượng...,supported,https://www.facebook.com/mps.gov/posts/pfbid02...,media/post_1_cmt_img_0.jpg,1,0,1,0,1,0,1,0,1.0,0.0
1,gemini-2.5-flash__fixed_size__clip__reranker_0,gemini-2.5-flash,fixed_size,clip,False,2,Các đối tượng cầm đầu đường dây lừa đảo đã thu...,supported,https://www.facebook.com/mps.gov/posts/pfbid02...,media/post_1_cmt_img_0.jpg,1,0,1,0,1,0,1,0,1.0,0.0
2,gemini-2.5-flash__fixed_size__clip__reranker_0,gemini-2.5-flash,fixed_size,clip,False,3,Thượng úy Nguyễn Đức Phước là Điều tra viên th...,refuted,https://www.facebook.com/mps.gov/posts/pfbid02...,media/post_1_cmt_img_0.jpg,0,0,1,0,1,0,7,0,0.0,0.0
3,gemini-2.5-flash__fixed_size__clip__reranker_0,gemini-2.5-flash,fixed_size,clip,False,4,Tổng số tiền bị chiếm đoạt bởi đường dây lừa đ...,nei,https://www.facebook.com/mps.gov/posts/pfbid02...,media/post_1_cmt_img_0.jpg,0,0,0,0,0,0,0,0,0.0,0.0
4,gemini-2.5-flash__fixed_size__clip__reranker_0,gemini-2.5-flash,fixed_size,clip,False,5,Các đối tượng lừa đảo đã bị bắt giữ vào ngày 1...,nei,https://www.facebook.com/mps.gov/posts/pfbid02...,media/post_1_cmt_img_0.jpg,0,0,0,0,0,0,0,0,0.0,0.0

## Merge With Existing Claim Metrics

In [5]:
claim_metrics = pd.read_csv(CLAIM_METRICS_CSV)
new_metric_cols = [c for c in claim_source_metrics.columns if c not in key_cols]
updated_claim_metrics = claim_metrics.merge(
    claim_source_metrics[key_cols + new_metric_cols],
    on=key_cols,
    how="left",
)
updated_claim_metrics.to_csv(UPDATED_CLAIM_METRICS_CSV, index=False, encoding="utf-8-sig")
print(updated_claim_metrics.shape)
print("Wrote", UPDATED_CLAIM_METRICS_CSV)
display(updated_claim_metrics.head())

(20688, 34)
Wrote D:\FactCheckPipeline\database\retrieval_eval_outputs\claim_metrics_long_with_source_metrics.csv

,experiment_id,refiner,collection,image_variant,use_reranker,id,claim,label,gold_text_url,gold_image_path,...,source_recall_at_3,image_source_recall_at_3,source_recall_at_10,image_source_recall_at_10,source_recall_at_20,image_source_recall_at_20,first_source_hit_rank,first_image_source_hit_rank,source_mrr_at_3,image_source_mrr_at_3
0,gemini-2.5-flash__fixed_size__clip__reranker_0,gemini-2.5-flash,fixed_size,clip,False,4,Tổng số tiền bị chiếm đoạt bởi đường dây lừa đ...,nei,https://www.facebook.com/mps.gov/posts/pfbid02...,media/post_1_cmt_img_0.jpg,...,0,0,0,0,0,0,0,0,0.0,0.0
1,gemini-2.5-flash__fixed_size__clip__reranker_0,gemini-2.5-flash,fixed_size,clip,False,6,Đường dây lừa đảo này chỉ nhắm mục tiêu vào ng...,nei,https://www.facebook.com/mps.gov/posts/pfbid02...,media/post_1_cmt_img_0.jpg,...,0,0,1,0,1,0,4,0,0.0,0.0
2,gemini-2.5-flash__fixed_size__clip__reranker_0,gemini-2.5-flash,fixed_size,clip,False,5,Các đối tượng lừa đảo đã bị bắt giữ vào ngày 1...,nei,https://www.facebook.com/mps.gov/posts/pfbid02...,media/post_1_cmt_img_0.jpg,...,0,0,0,0,0,0,0,0,0.0,0.0
3,gemini-2.5-flash__fixed_size__clip__reranker_0,gemini-2.5-flash,fixed_size,clip,False,1,Công an tỉnh Thái Bình đã khởi tố 10 đối tượng...,supported,https://www.facebook.com/mps.gov/posts/pfbid02...,media/post_1_cmt_img_0.jpg,...,1,0,1,0,1,0,1,0,1.0,0.0
4,gemini-2.5-flash__fixed_size__clip__reranker_0,gemini-2.5-flash,fixed_size,clip,False,2,Các đối tượng cầm đầu đường dây lừa đảo đã thu...,supported,https://www.facebook.com/mps.gov/posts/pfbid02...,media/post_1_cmt_img_0.jpg,...,1,0,1,0,1,0,1,0,1.0,0.0

## Update Summary Metrics

In [6]:
summary = pd.read_csv(SUMMARY_CSV)
experiment_cols = ["experiment_id", "refiner", "collection", "image_variant", "use_reranker"]
summary_source_metrics = updated_claim_metrics.groupby(experiment_cols, dropna=False)[new_metric_cols].mean().reset_index()
updated_summary = summary.merge(summary_source_metrics, on=experiment_cols, how="left")
updated_summary = updated_summary.sort_values(["evidence_recall_at_3", "source_recall_at_3", "mrr_at_3"], ascending=False)
updated_summary.to_csv(UPDATED_SUMMARY_CSV, index=False, encoding="utf-8-sig")
print(updated_summary.shape)
print("Wrote", UPDATED_SUMMARY_CSV)
display(updated_summary)

(16, 29)
Wrote D:\FactCheckPipeline\database\retrieval_eval_outputs\metrics_summary_with_source_metrics.csv

,experiment_id,refiner,collection,image_variant,use_reranker,num_claims,evidence_recall_at_3,text_recall_at_3,image_recall_at_3,full_recall_at_3,...,source_recall_at_3,image_source_recall_at_3,source_recall_at_10,image_source_recall_at_10,source_recall_at_20,image_source_recall_at_20,first_source_hit_rank,first_image_source_hit_rank,source_mrr_at_3,image_source_mrr_at_3
0,gpt4o_mini__semantic__clip__reranker_1,gpt4o_mini,semantic,clip,True,1293,0.921887,0.921887,0.000000,0.000000,...,0.825986,0.000000,0.888631,0.000000,0.904872,0.000000,1.596288,0.000000,0.759861,0.000000
1,gpt4o_mini__semantic__clip_finetuned__reranker_1,gpt4o_mini,semantic,clip_finetuned,True,1293,0.921887,0.921887,0.000000,0.000000,...,0.825986,0.000000,0.888631,0.000000,0.904872,0.000000,1.596288,0.000000,0.759861,0.000000
2,gemini-2.5-flash__semantic__clip__reranker_1,gemini-2.5-flash,semantic,clip,True,1293,0.921114,0.921114,0.000000,0.000000,...,0.831400,0.000000,0.894045,0.000000,0.917247,0.000000,1.675174,0.000000,0.770946,0.000000
3,gemini-2.5-flash__semantic__clip_finetuned__re...,gemini-2.5-flash,semantic,clip_finetuned,True,1293,0.921114,0.921114,0.000000,0.000000,...,0.831400,0.000000,0.894045,0.000000,0.917247,0.000000,1.675174,0.000000,0.770946,0.000000
4,gemini-2.5-flash__fixed_size__clip__reranker_1,gemini-2.5-flash,fixed_size,clip,True,1293,0.895592,0.895592,0.000000,0.000000,...,0.821346,0.000000,0.889404,0.000000,0.908739,0.000000,1.685228,0.000000,0.760634,0.000000
5,gemini-2.5-flash__fixed_size__clip_finetuned__...,gemini-2.5-flash,fixed_size,clip_finetuned,True,1293,0.895592,0.895592,0.000000,0.000000,...,0.821346,0.000000,0.889404,0.000000,0.908739,0.000000,1.685228,0.000000,0.760634,0.000000
6,gpt4o_mini__fixed_size__clip__reranker_1,gpt4o_mini,fixed_size,clip,True,1293,0.890178,0.890178,0.000000,0.000000,...,0.815159,0.000000,0.880897,0.000000,0.901005,0.000000,1.638824,0.000000,0.755994,0.000000
7,gpt4o_mini__fixed_size__clip_finetuned__rerank...,gpt4o_mini,fixed_size,clip_finetuned,True,1293,0.890178,0.890178,0.000000,0.000000,...,0.815159,0.000000,0.880897,0.000000,0.901005,0.000000,1.638824,0.000000,0.755994,0.000000
8,gemini-2.5-flash__semantic__clip__reranker_0,gemini-2.5-flash,semantic,clip,False,1293,0.885538,0.885538,0.001547,0.001547,...,0.775715,0.002320,0.866976,0.020108,0.897138,0.030936,1.971384,0.282289,0.690255,0.000773
9,gemini-2.5-flash__semantic__clip_finetuned__re...,gemini-2.5-flash,semantic,clip_finetuned,False,1293,0.885538,0.885538,0.000773,0.000773,...,0.775715,0.000773,0.866203,0.006961,0.894818,0.010054,1.941222,0.096674,0.690255,0.000258
10,gpt4o_mini__semantic__clip__reranker_0,gpt4o_mini,semantic,clip,False,1293,0.875483,0.875483,0.000000,0.000000,...,0.766435,0.000000,0.857695,0.015468,0.886311,0.023202,1.936582,0.215777,0.673885,0.000000
11,gpt4o_mini__semantic__clip_finetuned__reranker_0,gpt4o_mini,semantic,clip_finetuned,False,1293,0.875483,0.875483,0.000000,0.000000,...,0.766435,0.000000,0.856148,0.004640,0.884764,0.006187,1.924981,0.064965,0.673885,0.000000
12,gpt4o_mini__fixed_size__clip__reranker_0,gpt4o_mini,fixed_size,clip,False,1293,0.869296,0.869296,0.000000,0.000000,...,0.777262,0.000773,0.870843,0.016241,0.883991,0.023202,1.717711,0.212684,0.699278,0.000258
13,gpt4o_mini__fixed_size__clip_finetuned__rerank...,gpt4o_mini,fixed_size,clip_finetuned,False,1293,0.869296,0.869296,0.000000,0.000000,...,0.777262,0.000000,0.870070,0.003867,0.883217,0.006961,1.710750,0.081980,0.699278,0.000000
14,gemini-2.5-flash__fixed_size__clip__reranker_0,gemini-2.5-flash,fixed_size,clip,False,1293,0.868523,0.868523,0.000773,0.000773,...,0.778809,0.001547,0.872390,0.018561,0.894818,0.030162,1.846868,0.290797,0.703661,0.000516
15,gemini-2.5-flash__fixed_size__clip_finetuned__...,gemini-2.5-flash,fixed_size,clip_finetuned,False,1293,0.868523,0.868523,0.000773,0.000773,...,0.778809,0.000773,0.871616,0.006187,0.894045,0.009281,1.841454,0.084300,0.703661,0.000258

## Optional: Overwrite Original Summary Files

Run this cell only if you want the original filenames to include source metrics. The `_with_source_metrics.csv` files are already written above.

In [7]:
OVERWRITE_ORIGINALS = True

if OVERWRITE_ORIGINALS:
    updated_claim_metrics.to_csv(CLAIM_METRICS_CSV, index=False, encoding="utf-8-sig")
    updated_summary.to_csv(SUMMARY_CSV, index=False, encoding="utf-8-sig")
    print("Updated original claim_metrics_long.csv and metrics_summary.csv")
else:
    print("Original files left unchanged")

Updated original claim_metrics_long.csv and metrics_summary.csv